ALTER TABLE accounts ALTER COLUMN user_id TYPE VARCHAR(255)[];
ALTER TABLE expenses ALTER COLUMN user_id TYPE VARCHAR(255)[];
ALTER TABLE payment_dates ALTER COLUMN user_id TYPE VARCHAR(255)[];
ALTER TABLE settings ALTER COLUMN user_id TYPE VARCHAR(255);
ALTER TABLE settings ALTER COLUMN partner_id TYPE VARCHAR(255);