# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Quality control

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: 'Create .env file'
        env:
          DB_TABLE_PREFIX: ${{ secrets.DB_TABLE_PREFIX }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          GHUB_ID: ${{ secrets.GHUB_ID }}
          GHUB_SECRET: ${{ secrets.GHUB_SECRET }}
        run: |
          touch .env
          echo DB_TABLE_PREFIX="$DB_TABLE_PREFIX" >> .env
          echo POSTGRES_URL="$POSTGRES_URL" >> .env
          echo GITHUB_ID="$GHUB_ID" >> .env
          echo GITHUB_SECRET="$GHUB_SECRET" >> .env
        shell: bash

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: 'Lint'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm run lint
